# NUMPY

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.3


#Creating Arrays

In [3]:
# 1D array
a = np.array([10, 20, 30, 40])
print("1D Array:\n", a)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", b)

# Using built-in functions
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
randoms = np.random.rand(2, 3)

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nRandom:\n", randoms)

1D Array:
 [10 20 30 40]

2D Array:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random:
 [[0.85566002 0.89323716 0.21616198]
 [0.30625336 0.59778141 0.85150533]]


#Basic Operations

In [4]:
x = np.array([5, 10, 15])
y = np.array([2, 4, 6])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)

# Scalar operations
print("x squared:", x ** 2)

# Universal functions
print("Square root of x:", np.sqrt(x))
print("Exponential of y:", np.exp(y))

Addition: [ 7 14 21]
Subtraction: [3 6 9]
Multiplication: [10 40 90]
Division: [2.5 2.5 2.5]
x squared: [ 25 100 225]
Square root of x: [2.23606798 3.16227766 3.87298335]
Exponential of y: [  7.3890561   54.59815003 403.42879349]


#Indexing, Slicing, and Reshaping

In [5]:
arr = np.arange(1, 13)
print("Original Array:\n", arr)

# Reshape
arr2 = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", arr2)

# Slicing
print("\nFirst row:", arr2[0])
print("Element at row 2, col 3:", arr2[1, 2])
print("All rows, 2nd column:", arr2[:, 1])

# Boolean indexing
print("\nElements greater than 5:", arr2[arr2 > 5])

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Element at row 2, col 3: 7
All rows, 2nd column: [ 2  6 10]

Elements greater than 5: [ 6  7  8  9 10 11 12]


#Statistical and Matrix Operations

In [6]:
data = np.random.randint(1, 50, (4, 4))
print("Data:\n", data)

# Basic statistics
print("\nMean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Sum of each column:", np.sum(data, axis=0))

# Matrix operations
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

print("\nMatrix Multiplication:\n", np.dot(mat1, mat2))
print("\nTranspose of mat1:\n", mat1.T)
print("\nDeterminant of mat1:", np.linalg.det(mat1))

Data:
 [[39 45 48 14]
 [11  3  7 46]
 [14 41 28 44]
 [32 46 23 31]]

Mean: 29.5
Median: 31.5
Standard Deviation: 15.09138827278657
Sum of each column: [ 96 135 106 135]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of mat1:
 [[1 3]
 [2 4]]

Determinant of mat1: -2.0000000000000004


#Advanced (Broadcasting, Stacking, Random, Linspace)

In [7]:
# Broadcasting example
arr = np.arange(5)
print("Before Broadcasting:", arr)
arr = arr + 10
print("After Broadcasting:", arr)

# Horizontal & Vertical Stacking
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("\nHorizontal Stack:\n", np.hstack((a, b)))
print("\nVertical Stack:\n", np.vstack((a, b)))

# Random and linspace
rand_nums = np.random.randn(3, 3)
lin = np.linspace(0, 10, 5)
print("\nRandom Normal Values:\n", rand_nums)
print("\nLinearly spaced numbers:", lin)


Before Broadcasting: [0 1 2 3 4]
After Broadcasting: [10 11 12 13 14]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Random Normal Values:
 [[-0.13381282  1.29900118  0.1606169 ]
 [ 0.75956695 -0.62038703  0.48870868]
 [-0.56290837  0.468965    0.60631781]]

Linearly spaced numbers: [ 0.   2.5  5.   7.5 10. ]


#Masking, Sorting, and File Handling

In [8]:
data = np.random.randint(10, 100, (5, 5))
print("Original Data:\n", data)

# Masking
mask = data > 50
print("\nMask (values > 50):\n", mask)
print("\nFiltered values:", data[mask])

# Sorting
print("\nSorted row-wise:\n", np.sort(data, axis=1))
print("\nSorted column-wise:\n", np.sort(data, axis=0))

# File handling (save & load)
np.savetxt("my_data.csv", data, delimiter=",", fmt="%d")
loaded_data = np.loadtxt("my_data.csv", delimiter=",", dtype=int)
print("\nLoaded from file:\n", loaded_data)


Original Data:
 [[38 89 94 17 48]
 [56 11 95 88 33]
 [23 40 34 69 84]
 [36 81 12 98 88]
 [32 87 76 25 97]]

Mask (values > 50):
 [[False  True  True False False]
 [ True False  True  True False]
 [False False False  True  True]
 [False  True False  True  True]
 [False  True  True False  True]]

Filtered values: [89 94 56 95 88 69 84 81 98 88 87 76 97]

Sorted row-wise:
 [[17 38 48 89 94]
 [11 33 56 88 95]
 [23 34 40 69 84]
 [12 36 81 88 98]
 [25 32 76 87 97]]

Sorted column-wise:
 [[23 11 12 17 33]
 [32 40 34 25 48]
 [36 81 76 69 84]
 [38 87 94 88 88]
 [56 89 95 98 97]]

Loaded from file:
 [[38 89 94 17 48]
 [56 11 95 88 33]
 [23 40 34 69 84]
 [36 81 12 98 88]
 [32 87 76 25 97]]


#World Example (Temperature Conversion & Normalization)

In [9]:
# Temperature data (Celsius)
temps_c = np.array([25, 30, 35, 40, 45])

# Convert to Fahrenheit
temps_f = temps_c * 9/5 + 32
print("Temperature in Fahrenheit:", temps_f)

# Normalize dataset
values = np.array([5, 15, 25, 35, 45])
normalized = (values - np.min(values)) / (np.max(values) - np.min(values))
print("\nOriginal:", values)
print("Normalized:", normalized)


Temperature in Fahrenheit: [ 77.  86.  95. 104. 113.]

Original: [ 5 15 25 35 45]
Normalized: [0.   0.25 0.5  0.75 1.  ]
